name: cve-2021-36260

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use File from Repository
        run: |
          unzip nuclei.zip
          chmod 777 nuclei

      - name: nuclei
        run: ./nuclei -list input/targets.txt -stats -id CVE-2021-36260 -o vuln.txt

      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cve-2021-36260
          path: vuln.txt
