name: icp
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          sudo python -m pip install -r icp/requirements.txt
      - name: savexlsx
        run: 
          curl -O https://raw.githubusercontent.com/aliyungithub1234/test2/main/icp/wordpress.xlsx
      - name: icp run
        run: 
          python icp/icp_query.py
      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: icp_result
          path: wordpress.xlsx
